server:
  port: 8041
  servlet:
    context-path: /hub-manager-app

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,metrics

spring:
  profiles:
    default: local
    active: local

  application:
    name: hub-manager-app
